# SPDX-License-Identifier: MIT-0

FROM docker.io/golang:1.24.0-alpine3.21

RUN apk add --no-cache \
	# asdf prerequisites
	bash curl git \
	# project prerequisites
	jq make python3 py3-pip \
	&& \
	# configure git to operate in the mounted working directory
	git config --global --add safe.directory /asdf-yamllint

ENV ASDF_DATA_DIR="/.asdf"

WORKDIR /setup
COPY .tool-versions .

RUN go install github.com/asdf-vm/asdf/cmd/asdf@v0.16.2 \
	&& echo 'export PATH="/.asdf/shims:$''PATH"' > ~/.bashrc \
	&& asdf plugin add actionlint \
	&& asdf plugin add hadolint \
	&& asdf plugin add shellcheck \
	&& asdf plugin add shfmt \
	&& asdf install

ENTRYPOINT ["/bin/bash"]
